import type { FormDefinition } from "@/lib/trial-types";

export const STUDY = {
  protocol: "OS-NSCLC-201",
  title: "Phase II Oncology eSource Demonstration",
  phase: "Phase II",
  indication: "Non-small-cell lung cancer",
  version: "Protocol v1.2 · 18 Aug 2026",
  dataCut: "11 Sep 2026",
  sites: ["Chennai Oncology Centre", "Erode Research Unit", "Coimbatore Cancer Institute"],
};

export const formDefinitions: FormDefinition[] = [
  {
    key: "eligibility",
    shortLabel: "Screening",
    title: "Consent and eligibility",
    description: "Document consent chronology and protocol eligibility before any trial procedure.",
    domain: "DM / DS / IE",
    fields: [
      {
        id: "consent_date",
        label: "Informed consent date",
        type: "date",
        required: true,
        cdash: "RFICDTC",
        help: "Date the current consent version was signed.",
      },
      {
        id: "screening_date",
        label: "Screening assessment date",
        type: "date",
        required: true,
        cdash: "IEDTC",
      },
      {
        id: "age",
        label: "Age at consent",
        type: "number",
        required: true,
        unit: "years",
        min: 18,
        max: 90,
        cdash: "AGE",
      },
      {
        id: "sex",
        label: "Sex at birth",
        type: "select",
        required: true,
        options: ["Female", "Male"],
        cdash: "SEX",
      },
      {
        id: "histology_confirmed",
        label: "NSCLC histologically confirmed",
        type: "boolean",
        required: true,
        cdash: "IETESTCD",
      },
      {
        id: "ecog",
        label: "ECOG performance status",
        type: "select",
        required: true,
        options: ["0", "1", "2", "3", "4"],
        cdash: "EGORRES",
        help: "Protocol permits ECOG 0–1 at screening.",
      },
      {
        id: "eligibility_comment",
        label: "Eligibility assessment note",
        type: "textarea",
        placeholder: "Record source reviewed and any eligibility clarification.",
        span: 2,
        cdash: "IECOM",
      },
    ],
  },
  {
    key: "predose",
    shortLabel: "Pre-dose",
    title: "Pre-dose assessment",
    description: "Capture visit timing, anthropometry and safety laboratory results before treatment.",
    domain: "SV / VS / LB",
    fields: [
      {
        id: "visit_date",
        label: "Cycle 2 Day 1 visit date",
        type: "date",
        required: true,
        cdash: "SVSTDTC",
      },
      {
        id: "weight_kg",
        label: "Weight",
        type: "number",
        required: true,
        unit: "kg",
        min: 25,
        max: 180,
        cdash: "VSORRES",
      },
      {
        id: "height_cm",
        label: "Height",
        type: "number",
        required: true,
        unit: "cm",
        min: 120,
        max: 220,
        cdash: "VSORRES",
      },
      {
        id: "anc_x10e9_l",
        label: "Absolute neutrophil count",
        type: "number",
        required: true,
        unit: "×10⁹/L",
        min: 0,
        max: 30,
        cdash: "LBORRES",
      },
      {
        id: "platelets_x10e9_l",
        label: "Platelet count",
        type: "number",
        required: true,
        unit: "×10⁹/L",
        min: 0,
        max: 1000,
        cdash: "LBORRES",
      },
      {
        id: "creatinine_clearance_ml_min",
        label: "Calculated creatinine clearance",
        type: "number",
        required: true,
        unit: "mL/min",
        min: 0,
        max: 250,
        cdash: "LBSTRESN",
      },
      {
        id: "laboratory_collected_at",
        label: "Laboratory collection time",
        type: "datetime",
        required: true,
        cdash: "LBDTC",
      },
      {
        id: "treatment_planned",
        label: "Treatment planned after review",
        type: "boolean",
        required: true,
        cdash: "EXYN",
      },
    ],
  },
  {
    key: "treatment",
    shortLabel: "Treatment",
    title: "Study treatment administration",
    description: "Record protocol treatment, calculated dose and any interruption or modification.",
    domain: "EX",
    fields: [
      {
        id: "administered",
        label: "Study treatment administered",
        type: "boolean",
        required: true,
        cdash: "EXYN",
      },
      {
        id: "dose_mg_m2",
        label: "Protocol dose",
        type: "number",
        unit: "mg/m²",
        cdash: "EXDOSE",
      },
      {
        id: "actual_dose_mg",
        label: "Actual dose administered",
        type: "number",
        unit: "mg",
        cdash: "EXDOSE",
      },
      {
        id: "dose_start",
        label: "Administration start",
        type: "datetime",
        cdash: "EXSTDTC",
      },
      {
        id: "dose_end",
        label: "Administration end",
        type: "datetime",
        cdash: "EXENDTC",
      },
      {
        id: "dose_modified",
        label: "Dose modified",
        type: "boolean",
        cdash: "EXADJ",
      },
      {
        id: "modification_reason",
        label: "Modification or interruption reason",
        type: "textarea",
        placeholder: "Required if dose was modified or interrupted.",
        span: 2,
        cdash: "EXADJRS",
      },
    ],
  },
  {
    key: "adverse_event",
    shortLabel: "Safety",
    title: "Adverse event",
    description: "Capture event chronology, severity, seriousness, causality, action and outcome.",
    domain: "AE",
    fields: [
      {
        id: "ae_term",
        label: "Adverse event term",
        type: "text",
        placeholder: "Investigator-reported diagnosis or symptom",
        cdash: "AETERM",
      },
      {
        id: "ae_start_date",
        label: "Start date",
        type: "date",
        cdash: "AESTDTC",
      },
      {
        id: "ae_end_date",
        label: "End date",
        type: "date",
        cdash: "AEENDTC",
      },
      {
        id: "ae_grade",
        label: "CTCAE grade",
        type: "select",
        options: ["1", "2", "3", "4", "5"],
        cdash: "AETOXGR",
      },
      {
        id: "ae_serious",
        label: "Serious adverse event",
        type: "boolean",
        cdash: "AESER",
        help: "Seriousness and severity are assessed independently.",
      },
      {
        id: "seriousness_criterion",
        label: "Seriousness criterion",
        type: "select",
        options: [
          "Death",
          "Life-threatening",
          "Hospitalisation",
          "Disability or incapacity",
          "Congenital anomaly",
          "Other medically important event",
        ],
        cdash: "AESCONG",
      },
      {
        id: "causality",
        label: "Relationship to study treatment",
        type: "select",
        options: ["Not related", "Unlikely", "Possible", "Probable", "Definite"],
        cdash: "AEREL",
      },
      {
        id: "action_taken",
        label: "Action taken with study treatment",
        type: "select",
        options: ["None", "Dose reduced", "Interrupted", "Withdrawn", "Not applicable"],
        cdash: "AEACN",
      },
      {
        id: "outcome",
        label: "Outcome",
        type: "select",
        options: [
          "Recovered",
          "Recovering",
          "Not recovered",
          "Recovered with sequelae",
          "Fatal",
          "Unknown",
        ],
        cdash: "AEOUT",
      },
    ],
  },
];

export const formByKey = Object.fromEntries(
  formDefinitions.map((form) => [form.key, form]),
) as Record<(typeof formDefinitions)[number]["key"], FormDefinition>;
